# config/services.yaml

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # Configuration explicite pour AddressController
    App\Controller\AddressController:
        tags: ['controller.service_arguments']
        public: true