parameters:
    mailer.from_address: 'chouikhiabdallahpro@gmail.com'
    mailer.from_name: 'Bouazizi E-Commerce'
    twilio_account_sid: '%env(TWILIO_ACCOUNT_SID)%'
    twilio_auth_token: '%env(TWILIO_AUTH_TOKEN)%'
    twilio_phone_number: '%env(TWILIO_PHONE_NUMBER)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $projectDir: '%kernel.project_dir%'

    # Configuration globale
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Controller/AddressController.php'  # Exclure l'ancienne référence

    # Configuration spécifique pour les contrôleurs Admin
    App\Controller\Admin\:
        resource: '../src/Controller/Admin/'
        tags: ['controller.service_arguments']

    # Configuration spécifique pour les autres contrôleurs
    App\Controller\:
        resource: '../src/Controller/'
        exclude:
            - '../src/Controller/Admin/'
        tags: ['controller.service_arguments']

    # Configuration explicite pour SmtpMailService
    App\Service\SmtpMailService:
        arguments:
            $fromAddress: '%mailer.from_address%'
            $fromName: '%mailer.from_name%'
            
    # Configuration explicite pour InvoiceGenerator
    App\Service\InvoiceGenerator:
        arguments:
            $projectDir: '%kernel.project_dir%'
            
    # Configuration explicite pour PdfGenerator
    App\Service\PdfGenerator:
        arguments:
            $projectDir: '%kernel.project_dir%'
            
    # Configuration explicite pour TwilioService
    App\Service\TwilioService:
        arguments:
            $params: '@parameter_bag'

    # Configuration explicite pour OrderStateChangeListener
    App\EventListener\OrderStateChangeListener:
        tags:
            - { name: doctrine.orm.entity_listener, entity: App\Entity\Order }